baseURL = 'https://915411912.github.io/yeluzicaifangheji/'
languageCode = 'en-us'
title = '无敌懒羊羊'
theme = 'ananke'
publishDir = 'docs'

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

